In [ ]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
np.random.seed(123)

## QUESTION A
Simulate and generate the data for independent variable and dependent variable. 
The sample size n = 2000 students

In [ ]:
n = 2000
HS_math_GPA = np.random.uniform(2.0, 4.0, size=n)
HS_calculus = np.random.randint(2, size=n)
NTU_precalculus = np.random.randint(2, size=n)
error = np.random.normal(0, 0.5, size=n)
NTU_Calculus_grade = 0.3 + 0.7*HS_math_GPA + 0.3*HS_calculus + 0.1*NTU_precalculus + error
data = pd.DataFrame({'HS_math_GPA': HS_math_GPA,
                     'HS_calculus': HS_calculus,
                     'NTU_precalculus': NTU_precalculus,
                     'NTU_Calculus_grade': NTU_Calculus_grade})
print(data.head())


   HS_math_GPA  HS_calculus  NTU_precalculus  NTU_Calculus_grade
0     2.727030            0                0            2.783199
1     2.847466            1                0            1.350414
2     2.208873            1                0            2.145203
3     2.211210            1                1            0.941357
4     3.826896            1                1            3.685671


## Question B
use the dataset and estimate linear regression with "lm()" function.

In [ ]:
import statsmodels.api as sm
X = data[['HS_math_GPA', 'HS_calculus', 'NTU_precalculus']]
y = data['NTU_Calculus_grade']
model = sm.OLS(y, X).fit()
print(model.summary())

                                 OLS Regression Results                                
Dep. Variable:     NTU_Calculus_grade   R-squared (uncentered):                   0.963
Model:                            OLS   Adj. R-squared (uncentered):              0.963
Method:                 Least Squares   F-statistic:                          1.718e+04
Date:                Wed, 03 May 2023   Prob (F-statistic):                        0.00
Time:                        08:04:14   Log-Likelihood:                         -1523.0
No. Observations:                2000   AIC:                                      3052.
Df Residuals:                    1997   BIC:                                      3069.
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
                      coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------

## Question C
setup the matrix X (intercept plus independent variables) and variable y (independent variable)

In [ ]:
X = data[['HS_math_GPA', 'HS_calculus', 'NTU_precalculus']].values
X = np.column_stack((np.ones(len(X)), X))  # 0.3 * add an intercept term to X with value 0.3 0.3*
y = data['NTU_Calculus_grade'].values.reshape(-1, 1)  # reshape y to be a column vector
X

array([[1.        , 2.72703013, 0.        , 0.        ],
       [1.        , 2.84746622, 1.        , 0.        ],
       [1.        , 2.20887305, 1.        , 0.        ],
       ...,
       [1.        , 3.25786094, 1.        , 0.        ],
       [1.        , 2.26404706, 0.        , 1.        ],
       [1.        , 2.75491168, 1.        , 1.        ]])

In [ ]:
y

array([[2.78319908],
       [1.35041364],
       [2.14520265],
       ...,
       [3.25514304],
       [2.30050149],
       [3.38015255]])

## Question D:
compute matrix quantities (XTX)-1 by using "inv()" function in NumPy. C = XTX. What is the adjoint matrix adj(C)? det(C)? inv(C)? 

In [ ]:
# compute C = X^T * X
C = np.dot(X.T, X)
# compute the adjoint of C
adj_C = np.linalg.inv(C) * np.linalg.det(C)
det_C = np.linalg.det(C)
inv_C = np.linalg.inv(C)
print(C)
print(adj_C)
print(det_C)
print(inv_C)

[[ 2000.          5984.92144271   987.          1027.        ]
 [ 5984.92144271 18576.39174289  2967.57059498  3067.59645588]
 [  987.          2967.57059498   987.           508.        ]
 [ 1027.          3067.59645588   508.          1027.        ]]
[[ 4.95293878e+09 -1.49088548e+09 -2.85943742e+08 -3.58299616e+08]
 [-1.49088548e+09  4.99548298e+08 -1.40149567e+07  5.69269018e+06]
 [-2.85943742e+08 -1.40149567e+07  6.66199258e+08 -1.72616190e+06]
 [-3.58299616e+08  5.69269018e+06 -1.72616190e+06  6.66244060e+08]]
332844930257.15
[[ 1.48806196e-02 -4.47921942e-03 -8.59089973e-04 -1.07647611e-03]
 [-4.47921942e-03  1.50084394e-03 -4.21065649e-05  1.71031302e-05]
 [-8.59089973e-04 -4.21065649e-05  2.00153043e-03 -5.18608439e-06]
 [-1.07647611e-03  1.71031302e-05 -5.18608439e-06  2.00166504e-03]]


## Question e:
compute matrix quantities (XTX)-1XTy, residual, residual variances, standard errors of the covariance matrix.

In [ ]:
beta_hat = np.dot(np.dot(np.linalg.inv(np.dot(X.T, X)), X.T), y)
residuals = y - np.dot(X, beta_hat)
sigma_hat_squared = np.sum(residuals ** 2) / (n - X.shape[1]) # Compute residual variance sigma_hat^2
cov_beta_hat = sigma_hat_squared * np.linalg.inv(np.dot(X.T, X)) # Compute the standard errors of the covariance matrix
se_beta_hat = np.sqrt(np.diag(cov_beta_hat))

print('beta_hat:', beta_hat)
print('residuals:', residuals)
print('sigma_hat_squared:', sigma_hat_squared)
print('standard errors of beta_hat:', se_beta_hat)

beta_hat: [[0.41928036]
 [0.65253213]
 [0.3436095 ]
 [0.11266156]]
residuals: [[ 0.58444395]
 [-1.27053941]
 [-0.05904785]
 ...
 [ 0.36639425]
 [ 0.29119613]
 [ 0.70693276]]
sigma_hat_squared: 0.2631303404339688
standard errors of beta_hat: [0.0625743  0.01987253 0.02294915 0.02294992]


## Question F:
Compute the result of the estimated coefficeibt what is the results you observe

In [ ]:
true_beta = np.array([0.3, 0.7, 0.3, 0.1]).reshape(-1, 1)

# Use the lm() function to estimate the coefficients
lm_model = LinearRegression(fit_intercept=False).fit(X,y)
lm_beta = lm_model.coef_.T

# Create a DataFrame with the estimated coefficients
results = pd.DataFrame(
    data=np.concatenate((true_beta, beta_hat, lm_beta), axis=1),
    columns=['Truth', 'Manual', 'lm'],
    index=['Intercept', 'HS_math_GPA', 'HS_calculus', 'NTU_precalculus']
)
print(results)


                 Truth    Manual        lm
Intercept          0.3  0.419280  0.419280
HS_math_GPA        0.7  0.652532  0.652532
HS_calculus        0.3  0.343610  0.343610
NTU_precalculus    0.1  0.112662  0.112662


In [ ]:
# Compute residuals and RSS
residuals = y - y_hat
RSS = np.sum(residuals**2)

# Compute residual variance
n = X.shape[0]
p = X.shape[1] - 1
sigma_hat_sq = RSS / (n - p)

# Compute variance-covariance matrix of estimated coefficients
XTX_inv = np.linalg.inv(XTX)
var_beta_hat = sigma_hat_sq * XTX_inv

# Compute standard errors of estimated coefficients
se_beta_hat = np.sqrt(np.diag(var_beta_hat))

# Create table of results
results = pd.DataFrame({
    'Truth': beta,
    'Manual': beta_hat,
    'lm': lm_model.coef_
}, index=['Intercept', 'HS_math_GPA', 'HS_calculus', 'NTU_precalculus'])

results['Std. Error (Manual)'] = se_beta_hat


NameError: ignored